version: '3.0'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_sorvetes
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"